name: Marc Digital

on: [push]

jobs:

  package:
    name: Python Packaging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build Wheel
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload Wheel as Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: wheel-file
        path: dist/*.whl
        retention-days: 7
  
  install:
    name: Wheel Installation Test
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Add libraries
      run: |
        sudo apt install libgirepository1.0-dev gir1.2-gtk-4.0

    - name: Download Wheel Artifact
      uses: actions/download-artifact@v3
      with:
        name: wheel-file
        path: dist/

    - name: Install Wheel
      run: |
        pip install dist/*.whl
    